--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/WeaVerseStudio/VanillaWeather
build-by-default: true
branches:
- master
projects:
  VanillaWeather:
    path: ""
    icon: "image.png"
    compressBuilds: bool = true
...
